edition: 1.0.0
name: mall
access: default
vars:
  region: cn-hangzhou

# Define the Serverless-Devs services. Each service is a FC function.
services:
  mall-admin-web:
    component: devsapp/fc
    props:
      region: ${vars.region}
      # Define the AlibabaCloud FunctionCompute Service.
      service:
        name: mall-admin-web
        internetAccess: true
        # Let the serverless-devs create a shared logstore automatically.
        # All FC services share the same logstore.
        logConfig: auto 
      # Define the AlibabaCloud FunctionCompute Function.
      function:
        name: mall-admin-web
        description: The mall project based on SpringBoot+MyBatis. https://github.com/macrozheng/mall-admin-web
        caPort: 80
        memorySize: 1536
        handler: not-used # handler is invalid for custom container.
        timeout: 60
        runtime: custom-container
        customContainerConfig:
          image: registry.${vars.region}.aliyuncs.com/quanxi-hryang/mall-admin-web:1.0-SNAPSHOT
      triggers:
        - name: httpTrigger
          type: http
          config:
            authType: anonymous
            methods:
              - GET
              - POST
      customDomains:
        - domainName: auto
          protocol: HTTP
          routeConfigs:
            - path: /*
              serviceName: mall-admin-web
              functionName: mall-admin-web
              methods:
                - GET
                - POST


# https://github.com/devsapp/fc
